version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3308:3306"  # Maps host port 3307 to container port 3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql